### ISSUE TITLE
miners remove miner id weirdness

### ISSUE THREAD

**Issue by lanzafame** [glifio/cli#36]
```
❯ glif agent miners remove t018141 t3qu7qu32fnxutho5isph3wyx26z5qwroaj44s2mp7m2fepm23ofy6hb5hyzr3vdcut3uq7ufdshlab74u3giq
Removing miner f018141 from agent 0xD06e9Ab64bf6586088e0b08Bbd4BE7A54726FBcA by changing its owner address to f3qu7qu32fnxut
\panic: reflect: Call using address.Address as type uint64

goroutine 1 [running]:
reflect.Value.call({0x100b91a60?, 0xc00058f750?, 0x10004f876?}, {0x100cd5798, 0x4}, {0xc00012d800, 0x3, 0x100c489a0?})
	/usr/local/Cellar/go/1.20.4/libexec/src/reflect/value.go:442 +0x1a9f
reflect.Value.Call({0x100b91a60?, 0xc00058f750?, 0xc00063f900?}, {0xc00012d800?, 0x100ccf260?, 0xc00063f860?})
	/usr/local/Cellar/go/1.20.4/libexec/src/reflect/value.go:370 +0xbc
github.com/glifio/go-pools/util.WriteTx({0x78a61f063a3b3778?, 0x78430bcf?}, 0xc00007f0c0?, 0xc00007f0e0?, 0xc000154340, 0xc000154220, {0xc00063fa70, 0x2, 0xc0000c4dc0?}, {0x100b91a60, ...}, ...)
	/Users/lanzafame/pkg/mod/github.com/glifio/go-pools@v0.0.0-20230516020440-33a3863ee942/util/tx.go:41 +0x4fd
github.com/glifio/go-pools/sdk.(*fevmActions).AgentRemoveMiner(0xc000710ff0, {0x100efe350, 0xc000128018}, {0xd0, 0x6e, 0x9a, 0xb6, 0x4b, 0xf6, 0x58, ...}, ...)
	/Users/lanzafame/pkg/mod/github.com/glifio/go-pools@v0.0.0-20230516020440-33a3863ee942/sdk/agent_actions.go:196 +0x412
github.com/glifio/cli/cmd.glob..func13(0x101596f20, {0xc000460fc0, 0x2, 0x2?})
	/Users/lanzafame/src/github.com/glif-confidential/cli/cmd/agent_miners_remove.go:47 +0x386
github.com/spf13/cobra.(*Command).execute(0x101596f20, {0xc000460f80, 0x2, 0x2})
	/Users/lanzafame/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x101599760)
	/Users/lanzafame/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/lanzafame/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/glifio/cli/cmd.Execute()
	/Users/lanzafame/src/github.com/glif-confidential/cli/cmd/root.go:46 +0x25
main.main()
	/Users/lanzafame/src/github.com/glif-confidential/cli/main.go:21 +0x17

❯ glif agent miners remove t26xgeb6iphkdygca7i6y2baly5g6soklalln4gky t3qu7qu32fnxutho5isph3wyx26z5qwroaj44s2mp7m2fepm23ofy6hb5hyzr3vdcut3uq7ufdshlab74u3giq
Removing miner f26xgeb6iphkdygca7i6y2baly5g6soklalln4gky from agent 0xD06e9Ab64bf6586088e0b08Bbd4BE7A54726FBcA by changing i
-2023/05/17 13:12:07 cannot get id from non id address
```

**Comment by lanzafame** [comment]
Closing as this has been fixed.
